In [2]:
# installing libraries
!pip uninstall -y numpy tensorflow tensorflow_cpu tensorflow-intel keras
!pip install numpy==2.0.2 pandas==2.2.3 tensorflow==2.18.0

Found existing installation: numpy 2.3.1
Uninstalling numpy-2.3.1:
  Successfully uninstalled numpy-2.3.1

WARNING: Skipping tensorflow as it is not installed.
WARNING: Skipping tensorflow_cpu as it is not installed.
WARNING: Skipping tensorflow-intel as it is not installed.
WARNING: Skipping keras as it is not installed.

Collecting numpy==2.0.2
  Downloading numpy-2.0.2.tar.gz (18.9 MB)
     ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
     - -------------------------------------- 0.8/18.9 MB 15.4 MB/s eta 0:00:02
     ------------------- -------------------- 9.2/18.9 MB 34.7 MB/s eta 0:00:01
     -------------------------------- ------ 15.7/18.9 MB 33.7 MB/s eta 0:00:01
     ---------------------------------------- 18.9/18.9 MB 28.3 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      + C:\Users\helia\AppData\Local\Programs\Python\Python313\python.exe C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353\vendored-meson\meson\meson.py setup C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353 C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353\.mesonpy-ao61t74x -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353\.mesonpy-ao61t74x\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.99
      Source dir: C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353
      Build dir: C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353\.mesonpy-ao61t74x
      Build type: native build
      Project name: NumPy
      Project version: 2.0.2
      C compiler for the host machine: gcc (gcc 6.3.0 "gcc (MinGW.org GCC-6.3.0-1) 6.3.0")
      C linker for the host machine: gcc ld.bfd 2.28
      C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.28
      Cython compiler for the host machine: cython (cython 3.2.4)
      Host machine cpu family: x86
      Host machine cpu: x86

      ..\meson.build:28:4: ERROR: Problem encountered: NumPy requires GCC >= 8.4

      A full log can be found at C:\Users\helia\AppData\Local\Temp\pip-install-5a9aeqs1\numpy_992180dc74cd4c918d7c096a4f46b353\.mesonpy-ao61t74x\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\helia\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.18.0

In [4]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [5]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [6]:
# load data
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

The table shows that a 28-day-old concrete mix with a compressive strength of 79.99 MPa contains 540 cubic meters of cement, 162 cubic meters of water, 2.5 cubic meters of superplasticizer, 1040 cubic meters of coarse aggregate, and 676 cubic meters of fine aggregate, while containing no blast furnace slag or fly ash.

In [7]:
concrete_data.shape

(1030, 9)

In [8]:
# checking data for missing values
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [ ]:
concrete_data.isnull().sum()
# the data will look clean and ready

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

splitting data into predictors and target

In [11]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [12]:
# check if we split correctly
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

normalizing data

In [14]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [17]:
n_cols = predictors_norm.shape[1] # number of predictors

In [15]:
# importing keras packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [ ]:
# build a neural network
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1)) # output node
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [20]:
# test and train

#building the model
model = regression_model()

# train and test with fit method
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 47ms/step - loss: 1646.9209 - val_loss: 1142.6704
Epoch 2/100
23/23 - 0s - 14ms/step - loss: 1512.5255 - val_loss: 1022.0510
Epoch 3/100
23/23 - 0s - 10ms/step - loss: 1289.1271 - val_loss: 826.5166
Epoch 4/100
23/23 - 0s - 8ms/step - loss: 948.5624 - val_loss: 574.9525
Epoch 5/100
23/23 - 0s - 10ms/step - loss: 574.8063 - val_loss: 343.6696
Epoch 6/100
23/23 - 0s - 7ms/step - loss: 325.2027 - val_loss: 220.2589
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 246.6055 - val_loss: 183.7189
Epoch 8/100
23/23 - 0s - 12ms/step - loss: 223.0253 - val_loss: 172.4520
Epoch 9/100
23/23 - 0s - 9ms/step - loss: 207.1314 - val_loss: 168.5457
Epoch 10/100
23/23 - 0s - 7ms/step - loss: 195.9284 - val_loss: 165.1560
Epoch 11/100
23/23 - 0s - 8ms/step - loss: 187.9579 - val_loss: 164.5197
Epoch 12/100
23/23 - 0s - 8ms/step - loss: 181.3164 - val_loss: 162.4892
Epoch 13/100
23/23 - 0s - 10ms/step - loss: 175.6010 - val_loss: 161.5093
Epoch 14/100
23/23 - 0s - 11ms/step - loss: 170.6995 - val_loss: 162.9658
Epoch 15/100
23/23 - 0s - 13ms/step - loss: 166.6814 - val_loss: 160.5061
Epoch 16/100
23/23 - 0s - 12ms/step - loss: 162.5490 - val_loss: 159.6405
Epoch 17/100
23/23 - 0s - 11ms/step - loss: 159.5459 - val_loss: 160.3513
Epoch 18/100
23/23 - 0s - 11ms/step - loss: 156.5892 - val_loss: 161.1492
Epoch 19/100
23/23 - 0s - 13ms/step - loss: 154.3931 - val_loss: 162.4087
Epoch 20/100
23/23 - 0s - 16ms/step - loss: 152.5655 - val_loss: 160.1178
Epoch 21/100
23/23 - 0s - 13ms/step - loss: 150.9556 - val_loss: 161.7048
Epoch 22/100
23/23 - 0s - 12ms/step - loss: 148.1544 - val_loss: 162.2738
Epoch 23/100
23/23 - 0s - 10ms/step - loss: 146.3035 - val_loss: 163.2951
Epoch 24/100
23/23 - 0s - 13ms/step - loss: 144.8684 - val_loss: 162.1790
Epoch 25/100
23/23 - 0s - 12ms/step - loss: 143.7474 - val_loss: 162.4350
Epoch 26/100
23/23 - 0s - 11ms/step - loss: 142.2833 - val_loss: 165.9413
Epoch 27/100
23/23 - 0s - 20ms/step - loss: 140.3193 - val_loss: 167.6642
Epoch 28/100
23/23 - 0s - 21ms/step - loss: 139.2742 - val_loss: 161.4347
Epoch 29/100
23/23 - 1s - 25ms/step - loss: 137.4731 - val_loss: 164.7984
Epoch 30/100
23/23 - 0s - 21ms/step - loss: 136.4332 - val_loss: 166.0877
Epoch 31/100
23/23 - 0s - 22ms/step - loss: 135.7649 - val_loss: 167.0015
Epoch 32/100
23/23 - 0s - 18ms/step - loss: 133.5561 - val_loss: 164.8440
Epoch 33/100
23/23 - 1s - 23ms/step - loss: 132.9868 - val_loss: 165.2077
Epoch 34/100
23/23 - 0s - 19ms/step - loss: 131.0820 - val_loss: 165.4200
Epoch 35/100
23/23 - 0s - 19ms/step - loss: 129.7804 - val_loss: 166.5393
Epoch 36/100
23/23 - 1s - 32ms/step - loss: 128.0929 - val_loss: 164.6488
Epoch 37/100
23/23 - 1s - 26ms/step - loss: 126.6057 - val_loss: 165.9368
Epoch 38/100
23/23 - 1s - 28ms/step - loss: 125.7712 - val_loss: 166.7237
Epoch 39/100
23/23 - 0s - 17ms/step - loss: 123.7547 - val_loss: 166.0383
Epoch 40/100
23/23 - 0s - 17ms/step - loss: 121.3140 - val_loss: 163.6697
Epoch 41/100
23/23 - 0s - 17ms/step - loss: 119.5255 - val_loss: 167.5716
Epoch 42/100
23/23 - 0s - 13ms/step - loss: 117.8868 - val_loss: 165.2273
Epoch 43/100
23/23 - 0s - 14ms/step - loss: 115.8412 - val_loss: 163.0535
Epoch 44/100
23/23 - 0s - 16ms/step - loss: 114.9342 - val_loss: 163.7567
Epoch 45/100
23/23 - 0s - 17ms/step - loss: 112.4029 - val_loss: 163.3593
Epoch 46/100
23/23 - 0s - 14ms/step - loss: 110.8167 - val_loss: 162.9264
Epoch 47/100
23/23 - 0s - 17ms/step - loss: 108.5654 - val_loss: 159.3876
Epoch 48/100
23/23 - 0s - 17ms/step - loss: 106.7430 - val_loss: 157.9116
Epoch 49/100
23/23 - 0s - 14ms/step - loss: 104.1017 - val_loss: 157.2863
Epoch 50/100
23/23 - 0s - 17ms/step - loss: 102.3551 - val_loss: 157.4118
Epoch 51/100
23/23 - 0s - 17ms/step - loss: 100.4207 - val_loss: 152.2395
Epoch 52/100
23/23 - 0s - 17ms/step - loss: 98.2801 - val_loss: 148.6126
Epoch 53/100
23/23 - 0s - 17ms/step - loss: 95.0516 - val_loss: 149.0455
Epoch 54/100
23/23 - 0s - 17ms/step - loss: 92.6914 - val_loss: 144.5207
Epoch 55/100
23/23 - 0s - 15ms/step - loss: 89.5350 - val_loss: 145.9930
Epoch 56/100
23/23 - 0s - 16ms/step - loss: 86.7574 - val_loss: 140.0793
Epoch 57/100
23/23 - 0s - 17ms/step - loss: 84.0132 - val_loss: 137.1746
Epoch 58/100
23/23 - 0s - 17ms/step - loss: 81.7372 - val_loss: 135.3077
Epoch 59/100
23/23 - 0s - 18ms/step - loss: 78.8513 - val_loss: 134.4794
Epoch 60/100
23/23 - 0s - 17ms/step - loss: 75.3672 - val_loss: 133.4126
Epoch 61/100
23/23 - 0s - 15ms/step - loss: 71.8330 - val_loss: 130.8152
Epoch 62/100
23/23 - 0s - 14ms/step - loss: 69.0801 - val_loss: 127.7226
Epoch 63/100
23/23 - 0s - 16ms/step - loss: 66.2148 - val_loss: 125.3181
Epoch 64/100
23/23 - 0s - 17ms/step - loss: 63.2815 - val_loss: 123.5208
Epoch 65/100
23/23 - 0s - 17ms/step - loss: 61.0175 - val_loss: 118.3828
Epoch 66/100
23/23 - 0s - 17ms/step - loss: 58.8148 - val_loss: 117.5500
Epoch 67/100
23/23 - 0s - 17ms/step - loss: 56.6864 - val_loss: 120.9192
Epoch 68/100
23/23 - 0s - 13ms/step - loss: 54.9133 - val_loss: 121.2023
Epoch 69/100
23/23 - 0s - 17ms/step - loss: 53.0522 - val_loss: 106.6805
Epoch 70/100
23/23 - 0s - 17ms/step - loss: 51.9904 - val_loss: 113.4360
Epoch 71/100
23/23 - 0s - 17ms/step - loss: 49.8688 - val_loss: 117.2809
Epoch 72/100
23/23 - 0s - 18ms/step - loss: 48.4675 - val_loss: 106.9403
Epoch 73/100
23/23 - 0s - 14ms/step - loss: 48.1105 - val_loss: 117.0341
Epoch 74/100
23/23 - 0s - 16ms/step - loss: 46.4323 - val_loss: 111.9571
Epoch 75/100
23/23 - 0s - 18ms/step - loss: 45.4483 - val_loss: 111.9090
Epoch 76/100
23/23 - 0s - 18ms/step - loss: 44.7918 - val_loss: 111.1518
Epoch 77/100
23/23 - 0s - 17ms/step - loss: 43.9169 - val_loss: 114.7450
Epoch 78/100
23/23 - 0s - 18ms/step - loss: 42.5948 - val_loss: 111.0193
Epoch 79/100
23/23 - 0s - 14ms/step - loss: 41.9184 - val_loss: 114.7426
Epoch 80/100
23/23 - 0s - 15ms/step - loss: 41.5739 - val_loss: 106.5446
Epoch 81/100
23/23 - 0s - 17ms/step - loss: 40.5732 - val_loss: 113.6669
Epoch 82/100
23/23 - 0s - 17ms/step - loss: 39.7550 - val_loss: 108.2301
Epoch 83/100
23/23 - 0s - 17ms/step - loss: 39.1154 - val_loss: 116.7383
Epoch 84/100
23/23 - 0s - 16ms/step - loss: 38.7120 - val_loss: 115.5980
Epoch 85/100
23/23 - 0s - 15ms/step - loss: 37.8769 - val_loss: 114.1507
Epoch 86/100
23/23 - 0s - 16ms/step - loss: 37.8572 - val_loss: 119.3907
Epoch 87/100
23/23 - 0s - 16ms/step - loss: 37.1590 - val_loss: 109.6068
Epoch 88/100
23/23 - 0s - 18ms/step - loss: 38.0599 - val_loss: 116.3729
Epoch 89/100
23/23 - 0s - 16ms/step - loss: 36.2894 - val_loss: 112.5176
Epoch 90/100
23/23 - 0s - 18ms/step - loss: 36.0650 - val_loss: 115.7299
Epoch 91/100
23/23 - 0s - 15ms/step - loss: 35.7168 - val_loss: 119.7376
Epoch 92/100
23/23 - 0s - 16ms/step - loss: 35.4918 - val_loss: 119.1641
Epoch 93/100
23/23 - 0s - 16ms/step - loss: 34.7925 - val_loss: 110.3544
Epoch 94/100
23/23 - 0s - 17ms/step - loss: 35.2924 - val_loss: 119.2408
Epoch 95/100
23/23 - 0s - 17ms/step - loss: 34.1214 - val_loss: 123.4355
Epoch 96/100
23/23 - 0s - 17ms/step - loss: 34.1303 - val_loss: 113.1057
Epoch 97/100
23/23 - 0s - 16ms/step - loss: 33.7629 - val_loss: 114.6369
Epoch 98/100
23/23 - 0s - 17ms/step - loss: 33.4281 - val_loss: 121.2470
Epoch 99/100
23/23 - 0s - 17ms/step - loss: 33.3309 - val_loss: 115.4412
Epoch 100/100
23/23 - 0s - 18ms/step - loss: 32.8930 - val_loss: 122.9639

Changing model parameters

In [ ]:
def regression_model():
    input_colm = predictors_norm.shape[1] # number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [22]:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 3s - 113ms/step - loss: 1521.5531 - val_loss: 1001.3141
Epoch 2/100
29/29 - 0s - 12ms/step - loss: 620.5552 - val_loss: 232.9743
Epoch 3/100
29/29 - 0s - 6ms/step - loss: 245.2923 - val_loss: 229.0022
Epoch 4/100
29/29 - 0s - 6ms/step - loss: 207.6233 - val_loss: 195.8260
Epoch 5/100
29/29 - 0s - 8ms/step - loss: 184.4243 - val_loss: 181.6415
Epoch 6/100
29/29 - 0s - 7ms/step - loss: 172.0542 - val_loss: 166.0230
Epoch 7/100
29/29 - 0s - 7ms/step - loss: 159.8221 - val_loss: 155.3120
Epoch 8/100
29/29 - 0s - 8ms/step - loss: 147.9654 - val_loss: 139.0696
Epoch 9/100
29/29 - 0s - 7ms/step - loss: 137.2723 - val_loss: 138.2600
Epoch 10/100
29/29 - 0s - 7ms/step - loss: 127.7015 - val_loss: 126.1037
Epoch 11/100
29/29 - 0s - 7ms/step - loss: 112.6357 - val_loss: 108.9292
Epoch 12/100
29/29 - 0s - 8ms/step - loss: 96.3583 - val_loss: 93.0380
Epoch 13/100
29/29 - 0s - 9ms/step - loss: 81.8692 - val_loss: 92.5873
Epoch 14/100
29/29 - 0s - 9ms/step - loss: 71.3015 - val_loss: 70.5371
Epoch 15/100
29/29 - 0s - 9ms/step - loss: 65.8018 - val_loss: 63.2098
Epoch 16/100
29/29 - 0s - 8ms/step - loss: 62.7100 - val_loss: 66.0095
Epoch 17/100
29/29 - 0s - 7ms/step - loss: 56.6132 - val_loss: 70.0141
Epoch 18/100
29/29 - 0s - 6ms/step - loss: 53.7360 - val_loss: 58.2478
Epoch 19/100
29/29 - 0s - 6ms/step - loss: 47.6448 - val_loss: 51.2852
Epoch 20/100
29/29 - 0s - 6ms/step - loss: 44.7679 - val_loss: 48.9569
Epoch 21/100
29/29 - 0s - 7ms/step - loss: 44.6661 - val_loss: 46.1528
Epoch 22/100
29/29 - 0s - 8ms/step - loss: 43.3100 - val_loss: 43.6846
Epoch 23/100
29/29 - 0s - 7ms/step - loss: 39.4481 - val_loss: 45.1522
Epoch 24/100
29/29 - 0s - 12ms/step - loss: 38.5985 - val_loss: 48.6930
Epoch 25/100
29/29 - 0s - 9ms/step - loss: 35.9803 - val_loss: 41.4159
Epoch 26/100
29/29 - 0s - 8ms/step - loss: 34.4067 - val_loss: 42.9721
Epoch 27/100
29/29 - 0s - 7ms/step - loss: 35.0773 - val_loss: 48.7619
Epoch 28/100
29/29 - 0s - 6ms/step - loss: 31.2314 - val_loss: 32.8182
Epoch 29/100
29/29 - 0s - 7ms/step - loss: 30.2009 - val_loss: 34.1138
Epoch 30/100
29/29 - 0s - 7ms/step - loss: 28.9839 - val_loss: 36.6491
Epoch 31/100
29/29 - 0s - 9ms/step - loss: 28.2393 - val_loss: 44.3642
Epoch 32/100
29/29 - 0s - 8ms/step - loss: 28.4050 - val_loss: 30.8822
Epoch 33/100
29/29 - 0s - 9ms/step - loss: 26.5894 - val_loss: 31.9106
Epoch 34/100
29/29 - 0s - 10ms/step - loss: 27.8711 - val_loss: 33.3603
Epoch 35/100
29/29 - 0s - 8ms/step - loss: 26.6108 - val_loss: 32.3325
Epoch 36/100
29/29 - 0s - 9ms/step - loss: 24.4550 - val_loss: 31.1671
Epoch 37/100
29/29 - 0s - 9ms/step - loss: 24.0121 - val_loss: 30.6889
Epoch 38/100
29/29 - 0s - 10ms/step - loss: 24.3525 - val_loss: 29.3727
Epoch 39/100
29/29 - 0s - 9ms/step - loss: 23.8330 - val_loss: 30.2746
Epoch 40/100
29/29 - 0s - 9ms/step - loss: 23.5966 - val_loss: 36.6777
Epoch 41/100
29/29 - 0s - 10ms/step - loss: 22.3863 - val_loss: 30.1558
Epoch 42/100
29/29 - 0s - 9ms/step - loss: 22.7832 - val_loss: 31.3684
Epoch 43/100
29/29 - 0s - 12ms/step - loss: 21.5815 - val_loss: 28.9623
Epoch 44/100
29/29 - 0s - 7ms/step - loss: 20.9991 - val_loss: 25.3504
Epoch 45/100
29/29 - 0s - 4ms/step - loss: 21.8470 - val_loss: 27.7704
Epoch 46/100
29/29 - 0s - 5ms/step - loss: 21.4350 - val_loss: 25.5920
Epoch 47/100
29/29 - 0s - 7ms/step - loss: 20.3694 - val_loss: 24.5291
Epoch 48/100
29/29 - 0s - 7ms/step - loss: 21.2766 - val_loss: 24.9397
Epoch 49/100
29/29 - 0s - 4ms/step - loss: 19.9791 - val_loss: 32.3721
Epoch 50/100
29/29 - 0s - 4ms/step - loss: 20.7860 - val_loss: 23.9543
Epoch 51/100
29/29 - 0s - 5ms/step - loss: 19.4825 - val_loss: 22.9072
Epoch 52/100
29/29 - 0s - 5ms/step - loss: 18.9818 - val_loss: 23.1469
Epoch 53/100
29/29 - 0s - 6ms/step - loss: 19.0680 - val_loss: 28.3246
Epoch 54/100
29/29 - 0s - 6ms/step - loss: 18.9300 - val_loss: 22.5514
Epoch 55/100
29/29 - 0s - 6ms/step - loss: 18.9402 - val_loss: 23.4647
Epoch 56/100
29/29 - 0s - 7ms/step - loss: 18.9304 - val_loss: 27.1606
Epoch 57/100
29/29 - 0s - 6ms/step - loss: 18.2692 - val_loss: 28.0612
Epoch 58/100
29/29 - 0s - 5ms/step - loss: 17.6067 - val_loss: 26.4468
Epoch 59/100
29/29 - 0s - 7ms/step - loss: 17.6646 - val_loss: 23.0207
Epoch 60/100
29/29 - 0s - 5ms/step - loss: 18.3664 - val_loss: 23.7249
Epoch 61/100
29/29 - 0s - 5ms/step - loss: 17.2870 - val_loss: 21.8318
Epoch 62/100
29/29 - 0s - 6ms/step - loss: 17.1155 - val_loss: 23.6282
Epoch 63/100
29/29 - 0s - 9ms/step - loss: 16.5010 - val_loss: 20.4537
Epoch 64/100
29/29 - 0s - 9ms/step - loss: 18.5971 - val_loss: 25.8259
Epoch 65/100
29/29 - 0s - 9ms/step - loss: 17.7315 - val_loss: 20.1567
Epoch 66/100
29/29 - 0s - 9ms/step - loss: 16.1860 - val_loss: 19.8056
Epoch 67/100
29/29 - 0s - 9ms/step - loss: 16.3507 - val_loss: 19.0341
Epoch 68/100
29/29 - 0s - 9ms/step - loss: 16.2793 - val_loss: 18.3864
Epoch 69/100
29/29 - 0s - 9ms/step - loss: 15.7450 - val_loss: 19.9764
Epoch 70/100
29/29 - 0s - 10ms/step - loss: 15.6875 - val_loss: 20.9809
Epoch 71/100
29/29 - 0s - 9ms/step - loss: 15.7134 - val_loss: 21.9971
Epoch 72/100
29/29 - 0s - 9ms/step - loss: 16.1544 - val_loss: 19.0620
Epoch 73/100
29/29 - 0s - 8ms/step - loss: 15.7481 - val_loss: 18.3104
Epoch 74/100
29/29 - 0s - 4ms/step - loss: 14.9219 - val_loss: 20.4962
Epoch 75/100
29/29 - 0s - 4ms/step - loss: 15.3285 - val_loss: 18.0404
Epoch 76/100
29/29 - 0s - 5ms/step - loss: 15.5319 - val_loss: 17.3412
Epoch 77/100
29/29 - 0s - 5ms/step - loss: 16.2473 - val_loss: 19.9665
Epoch 78/100
29/29 - 0s - 5ms/step - loss: 15.0389 - val_loss: 18.0259
Epoch 79/100
29/29 - 0s - 5ms/step - loss: 14.3421 - val_loss: 17.5999
Epoch 80/100
29/29 - 0s - 5ms/step - loss: 14.2397 - val_loss: 17.5035
Epoch 81/100
29/29 - 0s - 7ms/step - loss: 15.0237 - val_loss: 20.0195
Epoch 82/100
29/29 - 0s - 5ms/step - loss: 15.0011 - val_loss: 20.1186
Epoch 83/100
29/29 - 0s - 6ms/step - loss: 15.6723 - val_loss: 17.8215
Epoch 84/100
29/29 - 0s - 5ms/step - loss: 15.5471 - val_loss: 16.2772
Epoch 85/100
29/29 - 0s - 5ms/step - loss: 13.9515 - val_loss: 16.8129
Epoch 86/100
29/29 - 0s - 5ms/step - loss: 15.1929 - val_loss: 18.0952
Epoch 87/100
29/29 - 0s - 6ms/step - loss: 14.8920 - val_loss: 15.6378
Epoch 88/100
29/29 - 0s - 6ms/step - loss: 14.7462 - val_loss: 18.8024
Epoch 89/100
29/29 - 0s - 7ms/step - loss: 15.8911 - val_loss: 19.8771
Epoch 90/100
29/29 - 0s - 8ms/step - loss: 15.1613 - val_loss: 16.5052
Epoch 91/100
29/29 - 0s - 8ms/step - loss: 13.1491 - val_loss: 17.8929
Epoch 92/100
29/29 - 0s - 7ms/step - loss: 13.1636 - val_loss: 16.5603
Epoch 93/100
29/29 - 0s - 8ms/step - loss: 13.2397 - val_loss: 15.1172
Epoch 94/100
29/29 - 0s - 8ms/step - loss: 13.2717 - val_loss: 18.2578
Epoch 95/100
29/29 - 0s - 12ms/step - loss: 13.0508 - val_loss: 16.7703
Epoch 96/100
29/29 - 0s - 8ms/step - loss: 13.1098 - val_loss: 15.5883
Epoch 97/100
29/29 - 0s - 9ms/step - loss: 13.7529 - val_loss: 15.1183
Epoch 98/100
29/29 - 0s - 8ms/step - loss: 13.7875 - val_loss: 15.4613
Epoch 99/100
29/29 - 0s - 9ms/step - loss: 13.2422 - val_loss: 14.9753
Epoch 100/100
29/29 - 0s - 8ms/step - loss: 14.5544 - val_loss: 15.0128

Increasing the number of hidden layers gives the model greater ability to capture complex patterns in the data, which can improve how well it fits the training set and, in turn, strengthen its predictions.

Using a smaller validation split leaves more data available for training, giving the model more examples from which to learn. With access to a larger training set, it can better recognize underlying trends and potentially achieve stronger overall performance.